// The instructions must match the buttons.
//
// src/config_controls.js is the one place a binding is written down. The game
// reads it (input.js) and so do the in-game instructions (config_menus.js
// builds the move screen's keyboard lines and pad tips from it), so those two
// can never disagree. Prose in markdown can — so this checks it, and can fix
// it:
//
//     node tools/check_controls.mjs          # verify, non-zero exit on drift
//     node tools/check_controls.mjs --fix    # rewrite the tables in place
//
// Each managed table sits between a pair of HTML comment markers. Everything
// outside them is yours to write; everything inside is generated.
//
// Run by `npm run check`.
import { readFile, writeFile } from "node:fs/promises";
import { controlsTable } from "../src/config_controls.js";

const START = "<!-- controls-table:start (generated by tools/check_controls.mjs — do not edit) -->";
const END = "<!-- controls-table:end -->";

const FILES = ["README.md", "docs/game-mechanics.md"];

const fix = process.argv.includes("--fix");
const want = `${START}\n${controlsTable()}\n${END}`;
let bad = 0;

for (const file of FILES) {
  const text = await readFile(file, "utf8");
  const from = text.indexOf(START);
  const to = text.indexOf(END);
  if (from < 0 || to < 0) {
    console.error(`FAIL ${file}: no controls-table markers. Add them around the controls table:\n${START}\n…\n${END}`);
    bad += 1;
    continue;
  }
  const have = text.slice(from, to + END.length);
  if (have === want) {
    console.log(`ok   ${file}`);
    continue;
  }
  if (fix) {
    await writeFile(file, text.slice(0, from) + want + text.slice(to + END.length));
    console.log(`fixed ${file}`);
    continue;
  }
  bad += 1;
  console.error(`FAIL ${file}: the controls table has drifted from src/config_controls.js.`);
  console.error("     Run: node tools/check_controls.mjs --fix");
}

if (bad) {
  console.error(`\n${bad} file(s) out of date with the control map.`);
  process.exit(1);
}
console.log("\ninstructions match the control map");
