#!/usr/bin/env node
// Import the Mech Mayhem sound bank and regenerate the SFX registry.
//
// The bank ships as a directory of mp3s plus a manifest.json mapping
//   name -> { file, category, sliced, loop }
// (categories: impact / weapon / character / ambience / ui / surface /
// movement / destruction / loop). This copies the files into assets/sfx/ and
// rewrites the generated block of src/config_audio.js from the manifest, so a
// re-import after upstream re-rolls a sound is mechanical: point this at the
// bank and run it.
//
//   node tools/sfx_intake.mjs [sourceDir]
//
// With no argument it regenerates the config from the manifest already in
// assets/sfx/ without copying anything.
//
// Retired mechs (owner Q2, docs/mech-conversion-plan.md) must not be
// referenced anywhere, so their signature files are neither copied nor
// registered. neon_buzz.mp3 is not part of the bank — it is the title sign's
// buzz, fetched by URL in ui.js — and is left alone.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const SFX_DIR = path.join(ROOT, "assets", "sfx");
const CONFIG = path.join(ROOT, "src", "config_audio.js");
const RETIRED = ["nova", "aegis"];

const BEGIN = "// >>> GENERATED by tools/sfx_intake.mjs — edit the manifest, not this block";
const END = "// <<< GENERATED";

const src = process.argv[2];
if (src) {
  const files = fs.readdirSync(src).filter((f) => f.endsWith(".mp3"));
  let copied = 0;
  for (const f of files) {
    if (RETIRED.some((m) => f.startsWith(m + "_"))) continue;
    fs.copyFileSync(path.join(src, f), path.join(SFX_DIR, f));
    copied++;
  }
  fs.copyFileSync(path.join(src, "manifest.json"), path.join(SFX_DIR, "manifest.json"));
  console.log(`copied ${copied} file(s) + manifest.json from ${src}`);
}

const manifest = JSON.parse(fs.readFileSync(path.join(SFX_DIR, "manifest.json"), "utf8"));

const lines = [];
let count = 0;
for (const [key, e] of Object.entries(manifest)) {
  if (RETIRED.some((m) => key.startsWith(m + "_"))) continue;
  if (!fs.existsSync(path.join(SFX_DIR, e.file))) {
    console.error(`manifest names a missing file: ${key} -> ${e.file}`);
    process.exitCode = 1;
    continue;
  }
  const extra = e.loop ? ", loop: true" : "";
  lines.push(`  ${key}: { file: ${JSON.stringify(e.file)}, category: ${JSON.stringify(e.category)}${extra} },`);
  count++;
}

const config = fs.readFileSync(CONFIG, "utf8");
const a = config.indexOf(BEGIN);
const b = config.indexOf(END);
if (a < 0 || b < 0) {
  console.error("config_audio.js has lost its generated-block markers");
  process.exit(1);
}
const next =
  config.slice(0, a + BEGIN.length) + "\n" + lines.join("\n") + "\n  " +
  config.slice(b);
if (next !== config) fs.writeFileSync(CONFIG, next);
console.log(`registered ${count} sound(s) in src/config_audio.js`);
