// GENERATED by tools/derive_attack_envelopes.mjs — do not edit by hand.
//
// Committed attack reach per character, in game px from the centre line,
// measured from their DELIVERED RIG posed at each attack's contact beat
// (body + weapon props; loader.measureAttackReach). Consumed by
// src/silhouette.js ahead of the sprite measurement: bones and prop shafts
// are exactly what can hit, where a sprite scan also reads energy clouds and
// painted smears as reach. Characters absent here (no rig, or held out of
// game) keep the sprite-derived measurement.
//
// Regenerate whenever models, manifests or pose libraries change:
//     node server.mjs &
//     node tools/derive_attack_envelopes.mjs
// tools/audit_hitboxes.mjs fails while this file is stale (--check).

export const MODEL_REACH = {
  "colossus": {"reach":86,"states":{"light":{"fwd":86,"top":209},"sideHeavy":{"fwd":77,"top":191},"upHeavy":{"fwd":55,"top":198},"downHeavy":{"fwd":50,"top":179},"crouchAttack":{"fwd":54,"top":216},"airLight":{"fwd":55,"top":299}}},
  "cranky": {"reach":99,"states":{"light":{"fwd":99,"top":169},"sideHeavy":{"fwd":72,"top":160},"upHeavy":{"fwd":42,"top":165},"downHeavy":{"fwd":43,"top":162},"crouchAttack":{"fwd":89,"top":161},"airLight":{"fwd":84,"top":235}}},
  "fenrir": {"reach":78,"states":{"light":{"fwd":42,"top":147},"sideHeavy":{"fwd":55,"top":138},"upHeavy":{"fwd":43,"top":165},"downHeavy":{"fwd":43,"top":162},"crouchAttack":{"fwd":60,"top":141},"airLight":{"fwd":78,"top":212}}},
  "frogger": {"reach":92,"states":{"light":{"fwd":68,"top":138},"sideHeavy":{"fwd":28,"top":181},"upHeavy":{"fwd":28,"top":181},"downHeavy":{"fwd":37,"top":177},"crouchAttack":{"fwd":92,"top":152},"airLight":{"fwd":72,"top":204}}},
  "glacier": {"reach":111,"states":{"light":{"fwd":64,"top":206},"sideHeavy":{"fwd":46,"top":206},"upHeavy":{"fwd":46,"top":206},"downHeavy":{"fwd":38,"top":205},"crouchAttack":{"fwd":111,"top":206},"airLight":{"fwd":54,"top":273}}},
  "inferno": {"reach":84,"states":{"light":{"fwd":47,"top":168},"sideHeavy":{"fwd":46,"top":193},"upHeavy":{"fwd":46,"top":193},"downHeavy":{"fwd":45,"top":183},"crouchAttack":{"fwd":84,"top":178},"airLight":{"fwd":47,"top":248}}},
  "jerry": {"reach":91,"states":{"light":{"fwd":91,"top":242},"sideHeavy":{"fwd":90,"top":169},"upHeavy":{"fwd":85,"top":184},"downHeavy":{"fwd":87,"top":177},"crouchAttack":{"fwd":88,"top":210},"airLight":{"fwd":90,"top":273}}},
  "konga": {"reach":112,"states":{"light":{"fwd":112,"top":167},"sideHeavy":{"fwd":23,"top":196},"upHeavy":{"fwd":38,"top":213},"downHeavy":{"fwd":38,"top":211},"crouchAttack":{"fwd":104,"top":174},"airLight":{"fwd":42,"top":303}}},
  "nullbot": {"reach":72,"states":{"light":{"fwd":39,"top":172},"sideHeavy":{"fwd":40,"top":175},"upHeavy":{"fwd":54,"top":173},"downHeavy":{"fwd":70,"top":179},"crouchAttack":{"fwd":72,"top":180},"airLight":{"fwd":42,"top":258}}},
  "rhino": {"reach":79,"states":{"light":{"fwd":54,"top":165},"sideHeavy":{"fwd":30,"top":196},"upHeavy":{"fwd":30,"top":196},"downHeavy":{"fwd":60,"top":192},"crouchAttack":{"fwd":79,"top":189},"airLight":{"fwd":57,"top":244}}},
  "saurion": {"reach":86,"states":{"light":{"fwd":83,"top":135},"sideHeavy":{"fwd":78,"top":130},"upHeavy":{"fwd":45,"top":147},"downHeavy":{"fwd":61,"top":144},"crouchAttack":{"fwd":86,"top":133},"airLight":{"fwd":84,"top":200}}},
  "tempest": {"reach":62,"states":{"light":{"fwd":42,"top":144},"sideHeavy":{"fwd":51,"top":154},"upHeavy":{"fwd":41,"top":176},"downHeavy":{"fwd":62,"top":183},"crouchAttack":{"fwd":60,"top":168},"airLight":{"fwd":45,"top":216}}},
  "titanus": {"reach":91,"states":{"light":{"fwd":89,"top":202},"sideHeavy":{"fwd":91,"top":225},"upHeavy":{"fwd":54,"top":205},"downHeavy":{"fwd":44,"top":196},"crouchAttack":{"fwd":53,"top":225},"airLight":{"fwd":54,"top":297}}},
  "tritone": {"reach":182,"states":{"light":{"fwd":178,"top":167},"sideHeavy":{"fwd":152,"top":216},"upHeavy":{"fwd":152,"top":216},"downHeavy":{"fwd":180,"top":180},"crouchAttack":{"fwd":182,"top":179},"airLight":{"fwd":181,"top":260}}},
  "viper": {"reach":93,"states":{"light":{"fwd":60,"top":147},"sideHeavy":{"fwd":91,"top":132},"upHeavy":{"fwd":93,"top":146},"downHeavy":{"fwd":34,"top":164},"crouchAttack":{"fwd":31,"top":199},"airLight":{"fwd":56,"top":218}}},
  "vulcan": {"reach":86,"states":{"light":{"fwd":48,"top":178},"sideHeavy":{"fwd":43,"top":174},"upHeavy":{"fwd":43,"top":174},"downHeavy":{"fwd":49,"top":167},"crouchAttack":{"fwd":86,"top":186},"airLight":{"fwd":54,"top":261}}},
  "wraith": {"reach":100,"states":{"light":{"fwd":48,"top":137},"sideHeavy":{"fwd":26,"top":140},"upHeavy":{"fwd":30,"top":186},"downHeavy":{"fwd":28,"top":183},"crouchAttack":{"fwd":84,"top":139},"airLight":{"fwd":100,"top":212}}},
};

export const ENVELOPE_INPUTS = {
  "manifest": "70cedc89d726",
  "sprites": "missing",
  "poses": "82fa840ca19b",
  "models": {
    "colossus": "4897362b6b45",
    "cranky": "44b516436434",
    "fenrir": "0fba029e89bd",
    "frogger": "ef814d46eddf",
    "glacier": "5ed1aeebca4d",
    "inferno": "87e6211fd256",
    "jerry": "c6fb11793e3c",
    "konga": "3db615cc355b",
    "nullbot": "4d627d20bbab",
    "rhino": "3fdc07addf1d",
    "saurion": "7aabdacb8868",
    "tempest": "4213468fccf9",
    "titanus": "4b8a14d5af3b",
    "tritone": "58472004f2f7",
    "viper": "00131928a97c",
    "vulcan": "f6e8087c124c",
    "wraith": "a265558aa6ab"
  }
};
