// GENERATED by tools/derive_com.mjs — do not edit by hand.
//
// Where each mech's mass sits, as a fraction of its DRAWN HEIGHT above its foot
// line. 0.5 is halfway up the body; larger is higher. This is the point that
// should hold still while everything else moves around it — the pivot a tumble
// turns about, the anchor an airborne body hangs from, the chest line an aim
// solves from, and the centre a launched hurtbox hangs on.
//
// Weighed off each mech's own triangles in its stance — the area-weighted
// centroid of the body, which is the centre of mass of a uniform shell. This is a
// transcription of the number the ENGINE measures at runtime
// (render3d/src/pose.js measureCom), so the simulation and the renderer cannot
// hold two opinions about where a mech's mass is. The renderer additionally
// carries it as an offset from the hip bone, so it follows the pose; this is the
// standing value, which is what the simulation scales by.
//
// Read by src/body_points.js BELOW a human decision in src/config_body_points.js
// and ABOVE the roster-wide COM_BODY_FRAC fallback: measurement beats the
// default, and somebody who has looked at the machine beats measurement.
//
// Regenerate whenever the models, the manifest or the pose stack change:
//     node server.mjs &
//     node tools/derive_com.mjs
// `--check` fails while this file is stale.

export const MODEL_COM = {
  "colossus": 0.4367,
  "cranky": 0.4968,
  "fenrir": 0.4969,
  "frogger": 0.5418,
  "glacier": 0.4848,
  "inferno": 0.5038,
  "jerry": 0.5095,
  "konga": 0.48,
  "nullbot": 0.4876,
  "rhino": 0.5009,
  "saurion": 0.4972,
  "tempest": 0.5137,
  "titanus": 0.477,
  "tritone": 0.5114,
  "viper": 0.5197,
  "vulcan": 0.508,
  "wraith": 0.5524,
};

// Fingerprint of everything the measurement above is a function of.
// `--check` fails while this file is stale.
export const COM_INPUTS = {
  "manifest": "70cedc89d726",
  "poses": "a2c1a6113a23",
  "models": {
    "colossus": "4897362b6b45",
    "cranky": "44b516436434",
    "fenrir": "0fba029e89bd",
    "frogger": "ef814d46eddf",
    "glacier": "5ed1aeebca4d",
    "inferno": "87e6211fd256",
    "jerry": "c6fb11793e3c",
    "konga": "3db615cc355b",
    "nullbot": "4d627d20bbab",
    "rhino": "3fdc07addf1d",
    "saurion": "7aabdacb8868",
    "tempest": "4213468fccf9",
    "titanus": "4b8a14d5af3b",
    "tritone": "58472004f2f7",
    "viper": "00131928a97c",
    "vulcan": "f6e8087c124c",
    "wraith": "a265558aa6ab"
  }
};
