// GENERATED by tools/derive_muzzles.mjs — do not edit by hand.
//
// Where a shot leaves each mech, in game px: x forward from the centre line,
// y from the foot line with UP NEGATIVE (the convention src/body_points.js
// and combat.js use). Measured from the `anchor_muzzle*` empty nodes Mech
// Mayhem's exporter ships in every mechs/*.glb, posed in that mech's own shoot
// clip at the release beat, taking whichever muzzle points further forward —
// the rigs do not agree about which one is "R".
//
// Read by src/body_points.js BELOW a human decision in src/config_body_points.js
// and ABOVE the reference-body fallback: measurement beats the roster default,
// and somebody who has looked at the machine beats measurement.
//
// Regenerate whenever the models, the manifest or the pose stack change:
//     node server.mjs &
//     node tools/derive_muzzles.mjs
// `--check` fails while this file is stale.

export const MODEL_MUZZLES = {
  "cranky": {"x":39,"y":-114,"anchor":"muzzleL","clip":"glb:shootLow"},
  "fenrir": {"x":64,"y":-105,"anchor":"muzzleR","clip":"glb:shoot"},
  "frogger": {"x":32,"y":-43,"anchor":"muzzleR","clip":"glb:spray"},
  "glacier": {"x":80,"y":-105,"anchor":"muzzleL","clip":"glb:shootLoopL"},
  "inferno": {"x":91,"y":-120,"anchor":"muzzleR","clip":"glb:shootLoop"},
  "jerry": {"x":27,"y":-134,"anchor":"muzzleR","clip":"glb:shootLoop"},
  "konga": {"x":23,"y":-146,"anchor":"muzzleR","clip":"glb:kongaLob"},
  "rhino": {"x":54,"y":-35,"anchor":"muzzleR","clip":"glb:shoot"},
  "saurion": {"x":118,"y":-54,"anchor":"muzzleR","clip":"glb:saurionQuillFan"},
  "tempest": {"x":57,"y":-38,"anchor":"muzzleR","clip":"glb:shoot"},
  "titanus": {"x":65,"y":-156,"anchor":"muzzleR","clip":"glb:fistLaunch"},
  "tritone": {"x":127,"y":-67,"anchor":"muzzleR","clip":"glb:tritoneBrace"},
  "viper": {"x":47,"y":-106,"anchor":"muzzleR","clip":"glb:shoot"},
  "vulcan": {"x":74,"y":-124,"anchor":"muzzleR","clip":"glb:gatlingLoop"},
  "wraith": {"x":102,"y":-103,"anchor":"muzzleR","clip":"glb:shoot"},
};

export const MUZZLE_INPUTS = {
  "manifest": "70cedc89d726",
  "poses": "807e71d69b2d",
  "models": {
    "colossus": "4897362b6b45",
    "cranky": "44b516436434",
    "fenrir": "0fba029e89bd",
    "frogger": "ef814d46eddf",
    "glacier": "5ed1aeebca4d",
    "inferno": "87e6211fd256",
    "jerry": "c6fb11793e3c",
    "konga": "3db615cc355b",
    "nullbot": "4d627d20bbab",
    "rhino": "3fdc07addf1d",
    "saurion": "7aabdacb8868",
    "tempest": "4213468fccf9",
    "titanus": "4b8a14d5af3b",
    "tritone": "58472004f2f7",
    "viper": "00131928a97c",
    "vulcan": "f6e8087c124c",
    "wraith": "a265558aa6ab"
  }
};
