// GENERATED by tools/derive_attack_envelopes.mjs — do not edit by hand.
//
// Committed attack reach per character, in game px from the centre line,
// measured from their DELIVERED RIG posed at each attack's contact beat
// (body + weapon props; loader.measureAttackReach). Consumed by
// src/silhouette.js ahead of the sprite measurement: bones and prop shafts
// are exactly what can hit, where a sprite scan also reads energy clouds and
// painted smears as reach. Characters absent here (no rig, or held out of
// game) keep the sprite-derived measurement.
//
// Regenerate whenever models, manifests or pose libraries change:
//     node server.mjs &
//     node tools/derive_attack_envelopes.mjs
// tools/audit_hitboxes.mjs fails while this file is stale (--check).

export const MODEL_REACH = {
  "colossus": {"reach":71,"states":{"light":{"fwd":71,"top":204},"sideHeavy":{"fwd":61,"top":199},"upHeavy":{"fwd":63,"top":171},"downHeavy":{"fwd":62,"top":161},"crouchAttack":{"fwd":66,"top":184},"airLight":{"fwd":64,"top":263}}},
  "cranky": {"reach":119,"states":{"light":{"fwd":96,"top":189},"sideHeavy":{"fwd":119,"top":189},"upHeavy":{"fwd":97,"top":183},"downHeavy":{"fwd":98,"top":181},"crouchAttack":{"fwd":97,"top":192},"airLight":{"fwd":98,"top":235}}},
  "fenrir": {"reach":50,"states":{"light":{"fwd":50,"top":150},"sideHeavy":{"fwd":47,"top":119},"upHeavy":{"fwd":46,"top":121},"downHeavy":{"fwd":47,"top":110},"crouchAttack":{"fwd":44,"top":129},"airLight":{"fwd":50,"top":208}}},
  "frogger": {"reach":60,"states":{"light":{"fwd":60,"top":146},"sideHeavy":{"fwd":52,"top":143},"upHeavy":{"fwd":52,"top":143},"downHeavy":{"fwd":57,"top":127},"crouchAttack":{"fwd":47,"top":137},"airLight":{"fwd":59,"top":146}}},
  "glacier": {"reach":80,"states":{"light":{"fwd":67,"top":197},"sideHeavy":{"fwd":80,"top":164},"upHeavy":{"fwd":80,"top":164},"downHeavy":{"fwd":73,"top":154},"crouchAttack":{"fwd":64,"top":196},"airLight":{"fwd":59,"top":273}}},
  "inferno": {"reach":75,"states":{"light":{"fwd":75,"top":177},"sideHeavy":{"fwd":61,"top":146},"upHeavy":{"fwd":61,"top":146},"downHeavy":{"fwd":61,"top":141},"crouchAttack":{"fwd":59,"top":173},"airLight":{"fwd":57,"top":247}}},
  "jerry": {"reach":89,"states":{"light":{"fwd":82,"top":255},"sideHeavy":{"fwd":82,"top":244},"upHeavy":{"fwd":73,"top":246},"downHeavy":{"fwd":80,"top":243},"crouchAttack":{"fwd":73,"top":253},"airLight":{"fwd":89,"top":266}}},
  "konga": {"reach":77,"states":{"light":{"fwd":76,"top":168},"sideHeavy":{"fwd":74,"top":137},"upHeavy":{"fwd":76,"top":153},"downHeavy":{"fwd":77,"top":148},"crouchAttack":{"fwd":60,"top":164},"airLight":{"fwd":76,"top":225}}},
  "nullbot": {"reach":78,"states":{"light":{"fwd":47,"top":177},"sideHeavy":{"fwd":78,"top":175},"upHeavy":{"fwd":47,"top":140},"downHeavy":{"fwd":46,"top":134},"crouchAttack":{"fwd":40,"top":157},"airLight":{"fwd":45,"top":181}}},
  "rhino": {"reach":71,"states":{"light":{"fwd":69,"top":172},"sideHeavy":{"fwd":64,"top":158},"upHeavy":{"fwd":64,"top":158},"downHeavy":{"fwd":61,"top":161},"crouchAttack":{"fwd":71,"top":166},"airLight":{"fwd":64,"top":172}}},
  "saurion": {"reach":87,"states":{"light":{"fwd":83,"top":133},"sideHeavy":{"fwd":73,"top":130},"upHeavy":{"fwd":43,"top":116},"downHeavy":{"fwd":85,"top":117},"crouchAttack":{"fwd":87,"top":132},"airLight":{"fwd":85,"top":134}}},
  "tempest": {"reach":105,"states":{"light":{"fwd":42,"top":152},"sideHeavy":{"fwd":105,"top":153},"upHeavy":{"fwd":42,"top":115},"downHeavy":{"fwd":42,"top":118},"crouchAttack":{"fwd":40,"top":153},"airLight":{"fwd":44,"top":153}}},
  "titanus": {"reach":80,"states":{"light":{"fwd":64,"top":196},"sideHeavy":{"fwd":80,"top":185},"upHeavy":{"fwd":69,"top":159},"downHeavy":{"fwd":69,"top":153},"crouchAttack":{"fwd":71,"top":172},"airLight":{"fwd":70,"top":245}}},
  "tritone": {"reach":125,"states":{"light":{"fwd":125,"top":174},"sideHeavy":{"fwd":98,"top":159},"upHeavy":{"fwd":98,"top":159},"downHeavy":{"fwd":98,"top":190},"crouchAttack":{"fwd":98,"top":185},"airLight":{"fwd":98,"top":257}}},
  "viper": {"reach":66,"states":{"light":{"fwd":40,"top":147},"sideHeavy":{"fwd":66,"top":130},"upHeavy":{"fwd":53,"top":144},"downHeavy":{"fwd":59,"top":101},"crouchAttack":{"fwd":59,"top":117},"airLight":{"fwd":65,"top":217}}},
  "vulcan": {"reach":67,"states":{"light":{"fwd":67,"top":180},"sideHeavy":{"fwd":65,"top":150},"upHeavy":{"fwd":65,"top":150},"downHeavy":{"fwd":61,"top":140},"crouchAttack":{"fwd":58,"top":174},"airLight":{"fwd":59,"top":260}}},
  "wraith": {"reach":76,"states":{"light":{"fwd":63,"top":141},"sideHeavy":{"fwd":58,"top":140},"upHeavy":{"fwd":54,"top":118},"downHeavy":{"fwd":55,"top":110},"crouchAttack":{"fwd":76,"top":127},"airLight":{"fwd":73,"top":205}}},
};

export const ENVELOPE_INPUTS = {
  "manifest": "23a7c1d909ff",
  "sprites": "missing",
  "poses": "41a616375631",
  "models": {
    "colossus": "31a727cf1855",
    "cranky": "1915fcbd5d8d",
    "fenrir": "eb2bccd4a431",
    "frogger": "cdbfccbe1696",
    "glacier": "9d36aee309ed",
    "inferno": "e512874fac50",
    "jerry": "c36eb4e8a8d0",
    "konga": "f8db35ab228a",
    "nullbot": "1c9cea4811d0",
    "rhino": "1d94edddeefc",
    "saurion": "0ddfd272cf5b",
    "tempest": "598eb2943228",
    "titanus": "3dd976fa84b1",
    "tritone": "51c95eeb62b9",
    "viper": "98d075f72ec5",
    "vulcan": "e31bdff7d906",
    "wraith": "44437ed74400"
  }
};
