// ---------------------------------------------------------------------------
// Sound-effect configuration — the registry, the mix, and the categories.
//
// Every sound the game can play is declared here as
//   key: { file, category, gain?, loop? }
// and referenced from code as `playSfx("key")` or from a move config as
// `sfx: "key"`. A key with no entry is a silent no-op, so a missing delivery
// degrades to silence rather than an error.
//
// The bank is Mech Mayhem's (imported by tools/sfx_intake.mjs from the
// robotworld repo's public/sfx — its manifest.json is the source of truth and
// travels with the files in assets/sfx/). Its naming scheme:
//
//   * generic camelCase events — hit, hitHeavy, block, whoosh, slam,
//     explosion, gatling, zap, powerup, cast, stingKO, countBeep, fightBell…
//   * per-mech signature takes — `<mechKey>_<event>.mp3` (fenrir_cast,
//     konga_ult…), played over the generic by playCharSfx / the grunt tables
//     in audio.js
//   * arena ambience beds — `amb_<stageKey>.mp3`, one per arena, looping
//   * surface steps — `step_<material>.mp3`
//   * held loops — booster_loop, burn_loop, shock_loop
//
// The JJK-era call names still used across src/ (playSfx("punch"),
// sfx: "slashHeavy" in characters.js…) resolve through SFX_ALIASES below, so
// the call sites migrate at leisure. `gain` is a per-sound trim applied on top
// of its category; the bank arrives normalised, so nothing needs one yet.
// ---------------------------------------------------------------------------

export const SFX_DIR = "assets/sfx/";

// ---------------------------------------------------------------- the mix
//
// Relative levels between the two buses and between categories. The Settings
// sliders scale the two MASTER values; everything else here is fixed balance
// that a player never sees.
//
// SFX sits well above music on purpose: this is a fighting game, and the hit
// feedback is information, not decoration. Music is atmosphere and should duck
// under a busy exchange rather than compete with it.
export const AUDIO_MIX = {
  // Default slider positions (0..1). Players override these in Settings.
  // See the git history of this file for how 0.77/0.55 were arrived at: both
  // were raised from much lower values by the same factor so every balance in
  // the mix survived, and MUSIC (which skips the master trim — see playMusic
  // in audio.js) is what caps how much further the pair can go.
  musicVolume: 0.77,
  sfxVolume: 0.55,

  // Hard ceiling applied after everything else, so a stacked frame — several
  // hits, a servo and a hazard in the same 100 ms — cannot clip.
  master: 0.9,

  // Per-category trim, adopted from Mech Mayhem's mix. Impact is the reference
  // at 1.0; everything else is placed relative to it. The categories are the
  // manifest's own.
  categories: {
    impact: 1.0,      // hits, blocks, slams — the loudest, most frequent layer
    movement: 0.55,   // jumps, landings, dashes: constant, must not fatigue
    weapon: 0.85,     // gatling, railgun, zap — projectiles and casts
    destruction: 1.0, // explosions and wreckage: the big payoffs
    ui: 0.7,          // menus, stings and bells
    character: 0.9,   // per-mech signature noises sit just under their hit
    surface: 0.5,     // material footsteps — texture, not information
    loop: 0.6,        // held beds: boosters, burning, shock
    ambience: 0.35,   // the arena's own bed, well under everything
  },
};

// How many one-shots may overlap. Past this, new calls are dropped rather than
// queued — a fighting game would otherwise pile up dozens of voices per second
// during a combo and turn to mush.
export const MAX_VOICES = 24;

// --------------------------------------------------------------- registry
//
// Generated from assets/sfx/manifest.json — rerun `node tools/sfx_intake.mjs`
// after changing the bank rather than editing the block by hand. Anything
// hand-tuned (a gain trim, say) belongs OUTSIDE the markers, in SFX_ALIASES or
// a wrapper entry.

export const SFX = {
  // >>> GENERATED by tools/sfx_intake.mjs — edit the manifest, not this block
  hit: { file: "hit.mp3", category: "impact" },
  hitHeavy: { file: "hitHeavy.mp3", category: "impact" },
  block: { file: "block.mp3", category: "impact" },
  whoosh: { file: "whoosh.mp3", category: "impact" },
  whooshBig: { file: "whooshBig.mp3", category: "impact" },
  slash: { file: "slash.mp3", category: "impact" },
  slam: { file: "slam.mp3", category: "impact" },
  land: { file: "land.mp3", category: "movement" },
  jump: { file: "jump.mp3", category: "movement" },
  dash: { file: "dash.mp3", category: "movement" },
  bodyfall: { file: "bodyfall.mp3", category: "impact" },
  servo: { file: "servo.mp3", category: "movement" },
  footstep: { file: "footstep.mp3", category: "movement" },
  footstepRun: { file: "footstepRun.mp3", category: "movement" },
  gatling: { file: "gatling.mp3", category: "weapon" },
  missile: { file: "missile.mp3", category: "weapon" },
  mortar: { file: "mortar.mp3", category: "weapon" },
  mortarBig: { file: "mortarBig.mp3", category: "weapon" },
  railgun: { file: "railgun.mp3", category: "weapon" },
  plasma: { file: "plasma.mp3", category: "weapon" },
  dart: { file: "dart.mp3", category: "weapon" },
  wave: { file: "wave.mp3", category: "weapon" },
  zap: { file: "zap.mp3", category: "weapon" },
  thunder: { file: "thunder.mp3", category: "weapon" },
  flame: { file: "flame.mp3", category: "weapon" },
  beam: { file: "beam.mp3", category: "weapon" },
  freeze: { file: "freeze.mp3", category: "weapon" },
  freezeBig: { file: "freezeBig.mp3", category: "weapon" },
  shatter: { file: "shatter.mp3", category: "weapon" },
  shard: { file: "shard.mp3", category: "weapon" },
  cast: { file: "cast.mp3", category: "weapon" },
  charge: { file: "charge.mp3", category: "weapon" },
  explosion: { file: "explosion.mp3", category: "destruction" },
  explosionBig: { file: "explosionBig.mp3", category: "destruction" },
  crumble: { file: "crumble.mp3", category: "destruction" },
  crumbleBig: { file: "crumbleBig.mp3", category: "destruction" },
  glassBreak: { file: "glassBreak.mp3", category: "destruction" },
  metalWreck: { file: "metalWreck.mp3", category: "destruction" },
  pause: { file: "pause.mp3", category: "ui" },
  countBeep: { file: "countBeep.mp3", category: "ui" },
  fightBell: { file: "fightBell.mp3", category: "ui" },
  stingRound: { file: "stingRound.mp3", category: "ui" },
  stingKO: { file: "stingKO.mp3", category: "ui" },
  stingWin: { file: "stingWin.mp3", category: "ui" },
  ultReady: { file: "ultReady.mp3", category: "ui" },
  powerup: { file: "powerup.mp3", category: "ui" },
  taunt: { file: "taunt.mp3", category: "ui" },
  amb_neon: { file: "amb_neon.mp3", category: "ambience", loop: true },
  amb_foundry: { file: "amb_foundry.mp3", category: "ambience", loop: true },
  amb_uptown: { file: "amb_uptown.mp3", category: "ambience", loop: true },
  amb_harbor: { file: "amb_harbor.mp3", category: "ambience", loop: true },
  amb_skyterrace: { file: "amb_skyterrace.mp3", category: "ambience", loop: true },
  amb_scrapyard: { file: "amb_scrapyard.mp3", category: "ambience", loop: true },
  amb_quarry: { file: "amb_quarry.mp3", category: "ambience", loop: true },
  amb_volcano: { file: "amb_volcano.mp3", category: "ambience", loop: true },
  amb_frozen: { file: "amb_frozen.mp3", category: "ambience", loop: true },
  amb_ruins: { file: "amb_ruins.mp3", category: "ambience", loop: true },
  amb_jungle: { file: "amb_jungle.mp3", category: "ambience", loop: true },
  amb_orbital: { file: "amb_orbital.mp3", category: "ambience", loop: true },
  step_water: { file: "step_water.mp3", category: "surface" },
  step_lava: { file: "step_lava.mp3", category: "surface" },
  step_ice: { file: "step_ice.mp3", category: "surface" },
  step_mud: { file: "step_mud.mp3", category: "surface" },
  step_oil: { file: "step_oil.mp3", category: "surface" },
  step_sand: { file: "step_sand.mp3", category: "surface" },
  step_grass: { file: "step_grass.mp3", category: "surface" },
  step_ash: { file: "step_ash.mp3", category: "surface" },
  step_crystal: { file: "step_crystal.mp3", category: "surface" },
  burn_loop: { file: "burn_loop.mp3", category: "loop", loop: true },
  shock_loop: { file: "shock_loop.mp3", category: "loop", loop: true },
  booster_loop: { file: "booster_loop.mp3", category: "loop", loop: true },
  howl: { file: "howl.mp3", category: "character" },
  cloak: { file: "cloak.mp3", category: "character" },
  chestBeat: { file: "chestBeat.mp3", category: "character" },
  stackVent: { file: "stackVent.mp3", category: "character" },
  torchIgnite: { file: "torchIgnite.mp3", category: "character" },
  arcTaunt: { file: "arcTaunt.mp3", category: "character" },
  holoGlitch: { file: "holoGlitch.mp3", category: "character" },
  iceTaunt: { file: "iceTaunt.mp3", category: "character" },
  iceThaw: { file: "iceThaw.mp3", category: "character" },
  batSwarm: { file: "batSwarm.mp3", category: "character" },
  growLoop: { file: "growLoop.mp3", category: "character" },
  sonicCroak: { file: "sonicCroak.mp3", category: "character" },
  clawSnap: { file: "clawSnap.mp3", category: "character" },
  gooSplat: { file: "gooSplat.mp3", category: "character" },
  fenrir_taunt: { file: "fenrir_taunt.mp3", category: "impact" },
  fenrir_cast: { file: "fenrir_cast.mp3", category: "impact" },
  fenrir_ult: { file: "fenrir_ult.mp3", category: "impact" },
  fenrir_hitHeavy: { file: "fenrir_hitHeavy.mp3", category: "impact" },
  jerry_servo: { file: "jerry_servo.mp3", category: "impact" },
  jerry_taunt: { file: "jerry_taunt.mp3", category: "impact" },
  jerry_cast: { file: "jerry_cast.mp3", category: "impact" },
  jerry_ult: { file: "jerry_ult.mp3", category: "impact" },
  frogger_taunt: { file: "frogger_taunt.mp3", category: "impact" },
  frogger_cast: { file: "frogger_cast.mp3", category: "impact" },
  frogger_ult: { file: "frogger_ult.mp3", category: "impact" },
  inferno_cast: { file: "inferno_cast.mp3", category: "impact" },
  inferno_ult: { file: "inferno_ult.mp3", category: "impact" },
  glacier_cast: { file: "glacier_cast.mp3", category: "impact" },
  glacier_ult: { file: "glacier_ult.mp3", category: "impact" },
  tempest_cast: { file: "tempest_cast.mp3", category: "impact" },
  tempest_ult: { file: "tempest_ult.mp3", category: "impact" },
  wraith_cast: { file: "wraith_cast.mp3", category: "impact" },
  wraith_hitHeavy: { file: "wraith_hitHeavy.mp3", category: "impact" },
  cranky_cast: { file: "cranky_cast.mp3", category: "impact" },
  cranky_ult: { file: "cranky_ult.mp3", category: "impact" },
  konga_hitHeavy: { file: "konga_hitHeavy.mp3", category: "impact" },
  konga_taunt: { file: "konga_taunt.mp3", category: "impact" },
  konga_ult: { file: "konga_ult.mp3", category: "impact" },
  viper_cast: { file: "viper_cast.mp3", category: "impact" },
  viper_ult: { file: "viper_ult.mp3", category: "impact" },
  saurion_taunt: { file: "saurion_taunt.mp3", category: "impact" },
  saurion_cast: { file: "saurion_cast.mp3", category: "impact" },
  saurion_ult: { file: "saurion_ult.mp3", category: "impact" },
  saurion_hitHeavy: { file: "saurion_hitHeavy.mp3", category: "impact" },
  titanus_ult: { file: "titanus_ult.mp3", category: "impact" },
  vulcan_cast: { file: "vulcan_cast.mp3", category: "impact" },
  nullbot_ult: { file: "nullbot_ult.mp3", category: "impact" },
  tritone_cast: { file: "tritone_cast.mp3", category: "impact" },
  tritone_taunt: { file: "tritone_taunt.mp3", category: "impact" },
  rhino_cast: { file: "rhino_cast.mp3", category: "impact" },
  // <<< GENERATED
};

// Element hit layers — played UNDER the normal hit sound when a hit's
// fxElement (config_fx.js / characters.js) matches. playSfx treats an
// unregistered name as silence, so an element with no row here is simply
// silent. Only the elements the mech roster actually declares are mapped.
export const ELEMENT_HIT_SFX = {
  machine: "servo",
  water: "wave",
  fire: "flame",
};

// ------------------------------------------------------- voice-era tables
//
// The JJK cast spoke: domain call-outs, Inumaki's cursed speech, alternate
// takes of every grunt. Mechs do not. The MACHINERY stays — specials.js,
// domains.js and the audio workbench all consume these tables, and a mech
// given a line later slots straight back in — but the data is gone with the
// recordings. An empty table is a working table: every lookup misses, every
// miss is silence-with-a-fallback (the grunt group), and nothing 404s.

// Per-character Domain Expansion (now: ultimate) call-out. Empty: a mech's
// ultimate announces itself with its `<mech>_ult` signature via the grunt
// path, not a spoken line.
export const DOMAIN_CALL = {};

// The line a fighter speaks when using a particular move, instead of their
// effort grunt. No mech has one.
export const MOVE_CALL = {};

// Handler-played signature sounds (a literal playSfx in specials.js /
// combat.js rather than a declared move sfx), recorded so the audio workbench
// can list them. The two JJK handlers still fire ("boogieClap", "seamCrack")
// and resolve through SFX_ALIASES; they belong to no mech, so no rows.
export const SIGNATURE_SFX = {};

// Alternate takes for the workbench to audition. The MM bank shipped one take
// per sound; re-rolls land here first and are promoted by hand.
export const SFX_ALTERNATES = {};

// Spoken-line lengths (seconds) — the frame data for line-as-wind-up moves.
// No lines, no rows; spokenLead() returns 0 for every move and nothing waits.
export const SPOKEN_LINES = {};

// How far into a line its move lands. Kept live (specials.js reads it even
// when every lookup above misses) at the tuning the feature shipped with.
export const SPOKEN_TIMING = {
  fraction: 0.8,
  min: 0.35,
  max: 2.2,
  commit: 0.5,
};

// ------------------------------------------------------------- the aliases
//
// Every name the game still calls that is not a key in the MM bank, mapped to
// the closest sound the bank has. This is the entire JJK->MM migration seam:
// call sites and move configs keep their names, entryFor (audio.js) resolves
// them here, and a name missing from BOTH tables is the bug this table exists
// to prevent — audit with `grep -rhoE 'playSfx\("[^"]+"|sfx: "[^"]+"' src/`.
export const SFX_ALIASES = {
  // ---- combat
  punch: "hit",
  melee: "hit",
  hitLight: "hit",
  hitMedium: "hit",
  hitCrit: "hitHeavy",
  blackFlash: "hitHeavy",   // the crit-of-crits: the heaviest impact we have
  slashHeavy: "hitHeavy",   // one slash take in the bank; heavy takes the thud
  swingWhiff: "whoosh",
  miss: "whoosh",
  guardHit: "block",
  block: "block",
  guardBreak: "shatter",
  parry: "zap",
  launch: "whooshBig",
  gone: "whooshBig",

  // ---- movement and match flow
  landing: "land",
  landSoft: "land",
  landHeavy: "slam",
  respawn: "powerup",
  meterFull: "ultReady",
  countdownReady: "countBeep",
  countdownGo: "fightBell",
  matchEnd: "stingWin",

  // ---- menus. The bank has no dedicated cursor blips, so the UI borrows its
  // nearest ui-category sounds: the count beep for movement, the pause blip
  // for anything dismissive, the pickup jingle for a confirmation.
  uiMove: "countBeep",
  uiSelect: "powerup",
  uiLockIn: "powerup",
  uiBack: "pause",
  uiDenied: "pause",
  uiPause: "pause",
  uiStart: "fightBell",

  // ---- energy, projectiles, summons, ultimates
  blast: "explosion",
  explosionSmall: "explosion",
  explosionLarge: "explosionBig",
  projectileFire: "cast",
  projectileHit: "zap",
  summonAppear: "cast",
  summonAttack: "hitHeavy",
  energyCharge: "charge",
  installActivate: "powerup",
  ult: "explosionBig",
  ultimate: "explosionBig",

  // ---- the domain moment (now the ultimate's staging — same call sites)
  domainExpansion: "thunder",
  domainBarrier: "charge",
  domainCollapse: "crumbleBig",
  domainRejected: "pause",
  domainInterior: "booster_loop", // the bed inside — startLoop makes it hold
  shield: "shock_loop",           // the held-guard hum
  fireBurnLoop: "burn_loop",

  // ---- handler-played JJK signatures still firing from specials/combat
  boogieClap: "hit",
  seamCrack: "crumble",

  // ---- stage hazards (Active Boards)
  hazardTelegraph: "charge",
  hazardWaterSurge: "wave",
  hazardFangSnap: "clawSnap",
  hazardBloom: "powerup",
  hazardBell: "fightBell",
  hazardFirePatch: "burn_loop",
  hazardElectricArc: "zap",
  hazardTrafficPass: "whooshBig",
  hazardSignalChirp: "countBeep",
  hazardCurseLatch: "gooSplat",
};
